name: Publish Snapshot

on:
  push:
    branches: [main]

jobs:
  publish:
    name: 'Publish Snapshot'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn
      - run: yarn --immutable
      - run: yarn changeset version --snapshot snapshot
      - run: yarn build:packages
      - run: yarn plugin import workspace-tools
      - run: yarn workspaces foreach --verbose --no-private npm publish --tolerate-republish --tag snapshot
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
