name: Publish Latest

on:
  push:
    branches: [main]

jobs:
  publish:
    name: 'Publish Latest'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn
      - run: yarn --immutable
      - run: yarn build:packages
      - run: yarn plugin import workspace-tools
      - run: yarn workspaces foreach --verbose --no-private npm publish --tolerate-republish --tag latest
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
